"""phase1 identity rbac

Revision ID: e78fd2eb4b8f
Revises: 25c4b4b2ca5e
Create Date: 2026-08-02 18:05:40.558757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78fd2eb4b8f'
down_revision: Union[str, None] = '25c4b4b2ca5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Client-generatable UUID (string form, portable across Postgres/SQLite) — never an auto-increment integer.'),
    sa.Column('device_id', sa.String(length=64), nullable=False, comment='Identifier of the device that created/last touched this row.'),
    sa.Column('created_by_id', sa.String(length=36), nullable=False, comment='Which user performed the action.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Incremented on every update; used for sync conflict detection.'),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCED', 'CONFLICT', 'FAILED', name='sync_status'), nullable=False, comment='SYNCED when written directly server-side; PENDING when queued from a device.'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_devices_user_device')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # batch mode: SQLite has no ALTER COLUMN TYPE, so this must go through a
    # table-recreate; batch mode also works unmodified against Postgres.
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=40),
            type_=sa.Enum('owner', 'accountant', 'store_keeper', 'shop_manager', 'cashier', 'super_admin', name='user_role'),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.Enum('owner', 'accountant', 'store_keeper', 'shop_manager', 'cashier', 'super_admin', name='user_role'),
            type_=sa.VARCHAR(length=40),
            existing_nullable=False,
        )
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
